#!/bin/sh

exec 1> /tmp/wz_mini_u_boot_initramfs.log 2>&1

set -x

echo "welcome to wz_mini initramfs"

# devtmpfs does not get automounted for initramfs
mount -t devtmpfs devtmpfs /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys

#Required delay on T20/T31
sleep 1

echo "Check for T20 platform"

if [ -b /dev/mtdblock10 ]; then

	echo "Found T20"

	#T20: Need to export the sd card enable gpio manually
	echo 43 > /sys/class/gpio/export
	echo in > /sys/class/gpio/gpio43/direction

	#T20: Insert required delay for sd card init
	sleep 3

	if ! [ -d /sys/class/gpio/gpio38 ]; then
		echo 38 > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio38/direction
		echo 1 > /sys/class/gpio/gpio38/value
	fi

	if ! [ -d /sys/class/gpio/gpio39 ]; then
		echo 39 > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio39/direction
		echo 1 > /sys/class/gpio/gpio39/value
	fi

	/led.sh &

	mkdir -p /sdcard
	mount -t vfat /dev/mmcblk0p1 /sdcard -o rw,umask=0000,dmask=0000

	cp /mtd0_v2_latest.bin.gz /tmp
	cd /tmp
	/bin/busybox gzip  -d mtd0_v2_latest.bin.gz
	/bin/busybox dd if=/dev/mtd0 of=/tmp/mtd0_orig.bin

	MTD0_ORIG=$(/bin/busybox md5sum /tmp/mtd0_orig.bin)


	check_u_boot_pre_flash() {
		if [[ "$(/bin/busybox md5sum /dev/mtd0)" == *"9a4dc35e081645f0b87baf7f8636ef8d"* ]]; then
			echo "u-boot new version match! exit"
			sync
			restart_device
		else
			flash_u_boot
		fi
	}

	check_u_boot_post_flash() {
		if [[ "$(/bin/busybox md5sum /dev/mtd0)" == *"9a4dc35e081645f0b87baf7f8636ef8d"* ]]; then
			echo "flash OK"
			erase_kernel
		else
			echo "flashsum doesn't match"
			restore_stock_u_boot
		fi
	}

	flash_u_boot() {
		/bin/busybox flashcp -v /tmp/mtd0_v2_latest.bin /dev/mtd0
		sync
		sleep 1
		check_u_boot_post_flash
	}

	check_stock_u_boot() {
		if [[ "$(/bin/busybox md5sum /dev/mtd0)" == *"$MTD0_ORIG"* ]]; then
			echo "restored stock OK"
			sync
			sleep 1
			erase_kernel
		else
			echo "fail"
			erase_kernel
		fi
	}

	restore_stock_u_boot() {
		/bin/busybox flashcp -v /tmp/mtd0_orig.bin /dev/mtd0
		sync
		sleep 1
		check_stock_u_boot
	}

	erase_kernel() {
		/bin/busybox flash_eraseall /dev/mtd1
		restart_device
	}

	restart_device() {
		sync
		cp /tmp/wz_mini_u_boot_initramfs.log /sdcard/wz_mini_u_boot_initramfs.log
		sync
		cd /
		umount /sdcard
		sleep 1
		exec busybox switch_root / /tmp/null
	}

	check_u_boot_pre_flash

else
	echo "Not T20"
	exec busybox switch_root / /tmp/null
	exit 1
	fi

